package com.example.voyage.payment.models;

import java.time.LocalDateTime;

/**
 * Model class representing a saved payment card in the stripe_cards table
 */
public class StripeCard {
    private int cardId;
    private int userId;
    private String stripePaymentMethodId;
    private String cardType;
    private String cardLast4;
    private int cardExpiryMonth;
    private int cardExpiryYear;
    private LocalDateTime createdAt;

    // Default constructor
    public StripeCard() {
    }

    // Constructor with all fields except ID and createdAt (generated by database)
    public StripeCard(int userId, String stripePaymentMethodId, String cardType,
            String cardLast4, int cardExpiryMonth, int cardExpiryYear) {
        this.userId = userId;
        this.stripePaymentMethodId = stripePaymentMethodId;
        this.cardType = cardType;
        this.cardLast4 = cardLast4;
        this.cardExpiryMonth = cardExpiryMonth;
        this.cardExpiryYear = cardExpiryYear;
    }

    // Getters and setters
    public int getCardId() {
        return cardId;
    }

    public void setCardId(int cardId) {
        this.cardId = cardId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getStripePaymentMethodId() {
        return stripePaymentMethodId;
    }

    public void setStripePaymentMethodId(String stripePaymentMethodId) {
        this.stripePaymentMethodId = stripePaymentMethodId;
    }

    public String getCardType() {
        return cardType;
    }

    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    public String getCardLast4() {
        return cardLast4;
    }

    public void setCardLast4(String cardLast4) {
        this.cardLast4 = cardLast4;
    }

    public int getCardExpiryMonth() {
        return cardExpiryMonth;
    }

    public void setCardExpiryMonth(int cardExpiryMonth) {
        this.cardExpiryMonth = cardExpiryMonth;
    }

    public int getCardExpiryYear() {
        return cardExpiryYear;
    }

    public void setCardExpiryYear(int cardExpiryYear) {
        this.cardExpiryYear = cardExpiryYear;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return cardType + " •••• " + cardLast4 + " (Expires: " + cardExpiryMonth + "/" + cardExpiryYear + ")";
    }
}
